### PR TITLE
Fix potential stall timing issue

### PR DESCRIPTION
**Pull request by skeggse**
The current stall implementation is vulnerable to the constraints of distributed time, and inconsistencies between workers’ clocks and possible clock drift.

Note that the code changes does not make the added tests pass, but they seemed good to have.

### CODE REVIEW

**Comment by bradvogel** [comment]
Other tests that use `stallInterval: 0` are breaking

**Comment by skeggse** [comment]
Yeah I noticed

**Comment by bradvogel** [comment]
@skeggse to finish unit tests next week

**Comment by skeggse** [comment]
Rolled into https://github.com/mixmaxhq/bee-queue/pull/10.

**Pull request merged**
